### ISSUE TITLE
Success criteria

### ISSUE THREAD

**Issue by cthorrez** [angelolovatto/gym-cartpole-swingup#13]
Hello, is there a definition for "solving this environment"? For example what is a good amount of rewards to receive in an episode?

**Comment by angelolovatto** [comment]
Hi @cthorrez and sorry for the **very** late reply. 

I couldn't find a good justification for any specific threshold. From my experience with CartPoleSwingUp-v1 (the one with positive rewards only), 400 seems to be a good amount since I've observed that policies in this range were able to balance the pole and keep the cart relatively close to the center of the screen
